
prototype ODlgUserPassword(STRING, STRING, BYREF STRING, BYREF STRING,INT,INT,INT,INT);
prototype ODlgDomainAccount(STRING, STRING, BYREF STRING, BYREF STRING, BYREF STRING,INT,INT);
prototype ODlgUserPasswordNoConfirm(STRING, STRING, BYREF STRING, BYREF STRING,INT,INT,INT,INT);





