prototype OCreateDSNEntry(STRING,STRING,STRING,STRING,STRING,STRING);
prototype ODBCCP32.SQLConfigDataSource (  HWND, SHORT, STRING, STRING );
prototype ODBCCP32.SQLCreateDataSource(HWND,STRING);
prototype ODBCCP32.SQLInstallerError(INT,INT,STRING,INT,INT);
prototype OTestDSN(STRING,STRING,STRING);
prototype OCheckForPreviousDSN(STRING,BYREF STRING,BYREF STRING,BYREF STRING);

